# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2025 Max Chernoff
FROM localhost:!!registry.port!!/fedora-iot-base:latest as base

FROM base as kernel
ARG COMPOSEFS_ID
RUN <<EOF
    set -euo pipefail

    # Install required packages
    dnf5 install \
        --assumeyes \
        --nodocs \
        --setopt=install_weak_deps=false \
        --setopt=keepcache=true \
        --use-host-config \
        sbsigntools \
        systemd-ukify

    # Determine kernel version
    kver="$(cd /usr/lib/modules && echo *)"
    kernel_path="/usr/lib/modules/$kver"

    # Create cmdline file
    echo "composefs=${COMPOSEFS_ID} root=gpt-auto rootflags=compress=zstd:3,noatime lockdown rw" > /etc/cmdline

    # Dracut configuration
    mkdir -p /etc/dracut.conf.d/
    echo "export DRACUT_NO_XATTR=1" > /etc/dracut.conf.d/no-xattr.conf
    dracut --verbose --force --reproducible --zstd --no-hostonly --kver="$kver" "$kernel_path/initramfs.img"

    # Build systemd-boot EFI executable
    mkdir -p /boot/efi/EFI/Linux/
    ukify build \
        --linux="$kernel_path/vmlinuz" \
        --initrd="$kernel_path/initramfs.img" \
        --cmdline="@/etc/cmdline" \
        --uname="$kver" \
        --measure \
        --output="/boot/efi/EFI/Linux/$kver.efi"

    mkdir -p /boot/efi/EFI/BOOT/ /boot/efi/EFI/systemd/
    cp /usr/lib/systemd/boot/efi/systemd-bootx64.efi /boot/efi/EFI/BOOT/BOOTX64.EFI
    cp /usr/lib/systemd/boot/efi/systemd-bootx64.efi /boot/efi/EFI/systemd/systemd-bootx64.efi

    mkdir -p /boot/efi/loader/
    echo 'timeout 1' > /boot/efi/loader/loader.conf

    bootc container lint || true
EOF

FROM base AS bootable
COPY --from=kernel /boot /boot
