# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff

# Base image
FROM registry.fedoraproject.org/fedora-minimal:!!fedora.version!! AS build

# Install dependencies
RUN dnf5 install \
    --assumeyes \
    --nodocs \
    --setopt=install_weak_deps=false \
    --setopt=keepcache=true \
    --use-host-config \
    rpm-ostree \
    selinux-policy-targeted \
    skopeo
