# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2025 Max Chernoff

# Base image
FROM quay.io/fedora/fedora-minimal:!!fedora.version!! AS build

# Install pip in the build environment
@dnf_install(
    python3-pip
)

# Install the base packages
@dnf_install[install_root=/mnt/build/](
    coreutils-single
    generic-release
    glibc-minimal-langpack
    knot-libs
    python3-prometheus_client
    python3-psutil
)

@run(
    pip3 install \
        --root=/mnt/build/ \
        --root-user-action=ignore \
        --break-system-packages \
        --no-cache-dir \
        'knot-exporter==3.4.*'  # TODO: questionable hack to work around old Fedora packages
)

@rpm_erase_all_except(
    .*lib.*
    .*python3.*
    basesystem
    filesystem
    setup
    generic-release
    gnutls
    p11-kit
    gmp
    nettle
)

# Create the new container
FROM scratch
COPY --from=build /mnt/build/ /
USER 1000:1000
ENTRYPOINT ["/usr/local/bin/knot-exporter"]
