# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff

#################
### Variables ###
#################

[variables]
builder = "/var/home/builder/"
etc = "/etc/"
max = "/var/home/max/"
physics = "/var/home/physics/"
repo = "/var/home/repo/maxchernoff.ca/"
repo-user = "/var/home/repo/"
tex = "/var/home/tex/"
usrlocal = "/usr/local/"
web = "/var/home/web/"
woodpecker = "/var/home/woodpecker/"


###############
### SELinux ###
###############

[selinux]
rules = """
fcontext --deleteall
fcontext --add --type container_file_t    '{repo-user}triggers(/.*)?'
fcontext --add --type container_file_t    '{web}caddy/logs(/.*)?'
fcontext --add --type container_ro_file_t '{etc}containers(/.*)?'
fcontext --add --type container_ro_file_t '{repo}builder/containers(/.*)?'
fcontext --add --type container_ro_file_t '{repo}web/caddy(/.*)?'
fcontext --add --type container_ro_file_t '{repo}web/dnscontrol(/.*)?'
fcontext --add --type container_ro_file_t '{repo}web/flask(/.*)?'
fcontext --add --type container_ro_file_t '{repo}web/goaccess(/.*)?'
fcontext --add --type container_ro_file_t '{repo}web/knot(/.*)?'
fcontext --add --type container_ro_file_t '{repo}web/maddy(/.*)?'
fcontext --add --type container_ro_file_t '{tex}context-installer/tex(/.*)?'
fcontext --add --type container_ro_file_t '{tex}texlive(/.*)?'
"""


############
### repo ###
############

[[permissions]]
base = "{repo-user}"
paths = ["*"]
owner = "repo"
permissions.other = ""

[[permissions]]
base = "/var/home/"
paths = ["repo/", "repo/maxchernoff.ca/", "repo/triggers/"]
owner = "repo"
permissions.other = "r"

[[permissions]]
base = "{repo}"
paths = ["*"]
owner = "repo"
permissions.other = "r"
recursive_permissions = true

[[permissions]]
base = "{repo}/"
paths = [".git*", "install-rules.toml"]
owner = "repo"
permissions.other = ""
recursive_permissions = true

[[folder]]
base = "{repo-user}"
paths = ["triggers"]
owner = "repo"
permissions.other = "r"

[[touch]]
base = "{repo-user}/triggers/"
paths = ["install-repo.trigger", "get-status.trigger", "get-status.output"]
owner = "repo"
permissions.max = "rw"
permissions.root = "rw"
permissions."web/1000" = "rw"
permissions.other = ""

[[folder]]
base = "{repo-user}"
paths = ["credentials"]
owner = "repo"
permissions.other = "r"
recursive_permissions = true


###########
### etc ###
###########

[[copy]]
source = "{repo}/etc/"
destination = "{etc}/"
paths = ["**/*"]
owner = "root"
permissions.other = "r"


#################
### usr/local ###
#################

[[copy]]
source = "{repo}/scripts/"
destination = "{usrlocal}/sbin/"
paths = ["web-install", "web-status", "notify-all", "ssh-restrict.sh"]
owner = "root"
permissions.other = "r"

[[copy]]
source = "{repo}/scripts/"
destination = "{usrlocal}/bin/"
paths = ["web-uptime", "email-failure"]
owner = "root"
permissions.other = "r"

[[copy]]
source = "{repo}/scripts/"
destination = "{usrlocal}/lib/python3.13/site-packages/"
paths = ["process_files/"]
owner = "root"
permissions.other = "r"


###########
### max ###
###########

[[permissions]]
base = "{max}"
paths = ["*"]
owner = "max"
permissions.other = ""

[[copy]]
source = "{repo}/max/"
destination = "{max}/"
paths = [".ssh/known_hosts", ".config/fish/config.fish"]
owner = "max"

# Risky, so we keep this commented out most of the time
# [[copy]]
# source = "{repo}/max/"
# destination = "{max}/"
# paths = [".ssh/authorized_keys",]
# owner = "max"


###########
### tex ###
###########

[[permissions]]
base = "{tex}"
paths = ["*"]
owner = "tex"
permissions.other = ""

[[permissions]]
base = "{repo}"
paths = ["tex/"]
owner = "repo"
permissions.tex = "r"
recursive_permissions = true

[[link]]
source = "{repo}/tex/"
destination = "{tex}/"
paths = [".config/systemd/user/"]
owner = "tex"

[[permissions]]
base = "{tex}"
paths = ["texlive/", "context-installer/tex/", "context/"]
owner = "tex"
permissions.other = "r"
recursive_permissions = false # Too slow to set permissions on all files


###########
### web ###
###########

[[permissions]]
base = "{web}"
paths = ["*"]
owner = "web"
permissions.other = ""

[[permissions]]
base = "{repo}"
paths = ["web/"]
owner = "repo"
permissions.web = "r"
recursive_permissions = true

[[link]]
source = "{repo}/web/"
destination = "{web}/"
paths = [".config/builder/", ".config/systemd/user/"]
permissions.web = "r"
owner = "root"

[[link]]
source = "{repo}/web/"
destination = "{web}/"
paths = [
    "caddy/*/",
    "flask",
    "goaccess",
    "knot/*/",
    "dnscontrol",
    "maddy/config",
]
permissions.web = "r"
permissions."web/root" = "r"
permissions."web/1000" = "r"
permissions."web/53" = "r"
permissions.max = "rw"
owner = "web"

[[folder]]
base = "{web}"
paths = [
    "caddy/config/",
    "caddy/data/",
    "caddy/logs/",
    "overleaf/overleaf/",
    "woodpecker/data/",
]
owner = "web/root"
permissions.web = "rw"

[[folder]]
base = "{web}"
paths = ["overleaf/redis/", "overleaf/mongo/"]
owner = "web/root"
permissions."web/999" = "rw"
permissions."web/root" = "rw"

[[folder]]
base = "{web}"
paths = ["overleaf/overleaf/"]
owner = "web"
permissions."web/33" = "rw"

[[permissions]]
base = "{web}/caddy/"
paths = ["etc/", "static/"]
permissions."web/root" = "r"
permissions."web" = "r"
owner = "repo"
recursive_permissions = true

[[touch]]
base = "{web}/caddy/"
paths = [
    "static/analytics/requests.tsv",
    "static/analytics/graphs",
    "logs/access.log",
]
permissions."web/root" = "rw"
permissions.web = "rw"
owner = "web/root"

[[permissions]]
base = "{web}/woodpecker/"
paths = ["data/"]
permissions."web/1000" = "rw"
permissions.web = "rw"
owner = "web/1000"
recursive_permissions = true

[[permissions]]
base = "{web}/"
paths = ["flask"]
owner = "repo"
permissions."web/1000" = "r"
permissions.web = "rw"
recursive_permissions = true

[[permissions]] # For scp
base = "{repo}"
paths = ["web/caddy/static/files"]
owner = "repo"
permissions.max = "rw"
permissions.web = "r"
permissions."web/root" = "r"
recursive_permissions = true

[[permissions]]
base = "{web}/"
paths = ["goaccess"]
owner = "repo"
permissions."web/root" = "r"
permissions.web = "r"
recursive_permissions = true

[[folder]]
base = "{web}"
paths = ["knot/storage/"]
owner = "web"
permissions.web = "rw"
permissions."web/53" = "rw"
permissions."web/root" = "rw"

[[permissions]]
base = "{repo}/web/knot/"
paths = ["config"]
owner = "repo"
permissions.web = "r"
permissions."web/53" = "r"
permissions."web/root" = "r"
recursive_permissions = true

[[permissions]]
base = "{web}/caddy/"
paths = ["logs/"]
owner = "web"
permissions.web = "rw"
permissions."web/root" = "rw"
recursive_permissions = true

[[permissions]]
base = "{repo}/web/"
paths = ["dnscontrol"]
owner = "repo"
permissions.web = "r"
permissions."web/root" = "r"
recursive_permissions = true

[[folder]]
base = "{web}"
paths = ["maddy/data/"]
owner = "web"
permissions.web = "rw"
permissions."web/1000" = "rw"

[[permissions]]
base = "{web}/maddy/"
paths = ["config"]
permissions."web/1000" = "r"
permissions."web" = "r"
owner = "repo"
recursive_permissions = true


##################
### woodpecker ###
##################

[[permissions]]
base = "{woodpecker}"
paths = ["*"]
owner = "woodpecker"
permissions.other = ""

[[permissions]]
base = "{repo}"
paths = ["woodpecker/"]
owner = "repo"
permissions.woodpecker = "r"
recursive_permissions = true

[[link]]
source = "{repo}/woodpecker/"
destination = "{woodpecker}/"
paths = [".config/systemd/user/", ".config/builder/"]
permissions.woodpecker = "r"

[[folder]]
base = "{woodpecker}"
paths = ["woodpecker/config/"]
owner = "woodpecker"

[[permissions]]
base = "{woodpecker}/woodpecker/"
paths = ["config/"]
permissions."woodpecker/1000" = "rw"
permissions.woodpecker = "rw"
owner = "woodpecker/1000"
recursive_permissions = true


###############
### builder ###
###############

[[permissions]]
base = "{builder}"
paths = ["*"]
owner = "builder"
permissions.other = ""

[[permissions]]
base = "{repo}"
paths = ["builder/"]
owner = "repo"
permissions.builder = "r"
recursive_permissions = true

[[link]]
source = "{repo}/builder/"
destination = "{builder}/"
paths = [".config/systemd/user/", "containers/"]
permissions.builder = "r"

[[folder]]
base = "{builder}/.cache/"
paths = ["podman-dnf/", "go-build/", "go-modules/", "rpm-ostree/"]
owner = "builder"


###############
### physics ###
###############

[[permissions]]
base = "{physics}"
paths = ["*"]
owner = "physics"
permissions.other = ""
permissions.max = "rw"
