# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff

#################
### Variables ###
#################

[variables]
etc = "/etc/"
max = "/var/home/max/"
repo = "/var/home/max/maxchernoff.ca/"
tex = "/var/home/tex/"
web = "/var/home/web/"
woodpecker = "/var/home/woodpecker/"


###############
### SELinux ###
###############

[selinux]
rules = """
fcontext --deleteall
fcontext --add --type container_ro_file_t '{tex}texlive(/.*)?'
fcontext --add --type container_ro_file_t '/var/home/max/maxchernoff.ca/web/caddy(/.*)?'
fcontext --add --type container_file_t    '{web}caddy/access.log'
"""


########################
### Base Permissions ###
########################

# max
[[permissions]]
base = "{max}"
paths = ["*"]
owner = "max"
permissions.other = ""
recursive_permissions = false

[[permissions]]
base = "{repo}"
paths = ["*"]
owner = "max"
permissions.other = ""
recursive_permissions = true

[[permissions]]
base = "{repo}/"
paths = [".git*", "install-rules.toml", "scripts/"]
owner = "max"
permissions.other = ""
recursive_permissions = true

# web
[[permissions]]
base = "{web}"
paths = ["*"]
owner = "web"
permissions.other = ""
recursive_permissions = false

[[permissions]]
base = "{repo}"
paths = ["web/"]
owner = "max"
permissions.web = "r"
recursive_permissions = true

# woodpecker
[[permissions]]
base = "{woodpecker}"
paths = ["*"]
owner = "woodpecker"
permissions.other = ""
recursive_permissions = false

[[permissions]]
base = "{repo}"
paths = ["woodpecker/"]
owner = "max"
permissions.woodpecker = "r"
recursive_permissions = true

# tex
[[permissions]]
base = "{tex}"
paths = ["*"]
owner = "tex"
permissions.other = ""
recursive_permissions = false

[[permissions]]
base = "{repo}"
paths = ["tex/"]
owner = "max"
permissions.tex = "r"
recursive_permissions = true


###########
### etc ###
###########

[[copy]]
source = "{repo}/etc/"
destination = "{etc}/"
paths = ["**/*"]
owner = "root"
permissions.other = "r"


###########
### max ###
###########

[[link]]
source = "{repo}/max/"
destination = "{max}/"
paths = [".ssh/known_hosts", ".config/fish/config.fish"]
owner = "max"

# [[copy]]
# source = "{repo}/max/"
# destination = "{max}/"
# paths = [".ssh/authorized_keys",]
# owner = "max"


###########
### tex ###
###########

[[link]]
source = "{repo}/tex/"
destination = "{tex}/"
paths = [".config/systemd/user/"]
owner = "tex"

[[permissions]]
base = "{tex}"
paths = ["texlive/"]
owner = "tex"
permissions.other = "r"
recursive_permissions = false


###########
### web ###
###########

[[link]]
source = "{repo}/web/"
destination = "{web}/"
paths = [".config/containers/", ".config/systemd/user/"]
permissions.web = "r"
owner = "root"

[[link]]
source = "{repo}/web/"
destination = "{web}/"
paths = ["caddy/*/"]
permissions.web = "r"
permissions."web/root" = "r"
permissions.max = "rw"
owner = "web"

[[folder]]
base = "{web}"
paths = [
    "caddy/config/",
    "caddy/data/",
    "overleaf/overleaf/",
    "woodpecker/data/",
]
owner = "web/root"
permissions.web = "rw"

[[folder]]
base = "{web}"
paths = ["overleaf/redis/", "overleaf/mongo/"]
owner = "web/root"
permissions."web/999" = "rw"
permissions."web/root" = "rw"

[[folder]]
base = "{web}"
paths = ["overleaf/overleaf/"]
owner = "web"
permissions."web/33" = "rw"

[[permissions]]
base = "{web}/caddy/"
paths = ["etc/", "static/"]
permissions."web/root" = "r"
permissions."web" = "r"
owner = "max"
recursive_permissions = true

[[permissions]]
base = "{web}/caddy/"
paths = [
    "static/analytics/requests.tsv",
    "static/analytics/graphs",
    "access.log",
]
permissions."web/root" = "rw"
permissions.web = "rw"
owner = "web"
recursive_permissions = true

[[permissions]]
base = "{web}/woodpecker/"
paths = ["data/"]
permissions."web/root" = "rw"
permissions.web = "rw"
owner = "web"


##################
### woodpecker ###
##################

[[link]]
source = "{repo}/woodpecker/"
destination = "{woodpecker}/"
paths = [".config/systemd/user/", ".config/containers/"]
permissions.woodpecker = "r"

[[folder]]
base = "{woodpecker}"
paths = ["woodpecker/config/"]
owner = "woodpecker"

[[permissions]]
base = "{woodpecker}/woodpecker/"
paths = ["config/"]
permissions."woodpecker/root" = "rw"
owner = "woodpecker"
