# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff

#################
### Variables ###
#################

[variables]
etc = "/etc/"
max = "/var/home/max/"
repo = "/var/home/max/maxchernoff.ca/"
tex = "/var/home/tex/"
web = "/var/home/web/"
woodpecker = "/var/home/woodpecker/"


############
### Repo ###
############

[[permissions]]
base = "{repo}/"
paths = [".git*", "install-rules.toml", "scripts/"]
permissions.other = ""


###########
### etc ###
###########

[[copy]]
source = "{repo}/etc/"
destination = "{etc}/"
paths = ["**/*"]
permissions.other = "r"

[[permissions]]
base = "{etc}/"
paths = ["firewalld/"]
selinux_type = "firewalld_etc_rw"

[[permissions]]
base = "{etc}/"
paths = ["snapper/configs/home", "sysconfig/snapper"]
selinux_type = "snapperd_conf"

[[permissions]]
base = "{etc}/"
paths = ["ssh/sshd_config.d/", "rpm-ostreed.conf"]
selinux_type = "etc"

[[permissions]]
base = "{etc}/"
paths = ["sysctl.d/"]
selinux_type = "system_conf"

[[permissions]]
base = "{etc}/"
paths = ["systemd/"]
selinux_type = "systemd_unit_file"

[[permissions]]
base = "{etc}/"
paths = ["localtime"]
selinux_type = "locale"


###########
### max ###
###########

[[link]]
source = "{repo}/max/"
destination = "{max}/"
paths = [".ssh/known_hosts", ".config/fish/config.fish"]
owner = "max"

# [[copy]]
# source = "{repo}/max/"
# destination = "{max}/"
# paths = [".ssh/authorized_keys",]
# owner = "max"


###########
### tex ###
###########

[[link]]
source = "{repo}/tex/"
destination = "{tex}/"
paths = [".config/systemd/user/"]
owner = "tex"


###########
### web ###
###########

[[link]]
source = "{repo}/web/"
destination = "{web}/"
paths = [".config/containers/", ".config/systemd/user/", "caddy/*/"]
permissions.web = "r"
permissions.589824 = "r"                                             # TODO
owner = "web"

[[folder]]
base = "{web}"
paths = [
    "caddy/config/",
    "caddy/data/",
    "overleaf/overleaf/",
    "woodpecker/data/",
]
owner = "589824"
permissions.web = "rw"

[[folder]]
base = "{web}"
paths = ["overleaf/redis/", "overleaf/mongo/"]
owner = "589824"
permissions.590823 = "rw"
permissions.589824 = "rw"

[[folder]]
base = "{web}"
paths = ["overleaf/overleaf/"]
permissions.589857 = "rw"

[[permissions]]
base = "{web}/caddy/"
paths = ["etc/", "static/"]
selinux_type = "container_ro_file"
permissions.589824 = "r"           # TODO
owner = "web"

[[permissions]]
base = "{web}/caddy/"
paths = [
    "static/analytics/requests.tsv",
    "static/analytics/graphs",
    "access.log",
]
selinux_type = "container_file"
permissions.589824 = "rw" # TODO
permissions.web = "rw"
owner = "web"

[[permissions]]
base = "{web}/woodpecker/"
paths = ["data/"]
permissions.589824 = "rw"  # TODO
permissions.web = "rw"
owner = "web"


##################
### woodpecker ###
##################

[[link]]
source = "{repo}/woodpecker/"
destination = "{woodpecker}/"
paths = [".config/systemd/user/", ".config/containers/"]

[[folder]]
base = "{woodpecker}"
paths = ["woodpecker/config/"]
owner = "woodpecker"

[[permissions]]
base = "{woodpecker}/woodpecker/"
paths = ["config/"]
permissions.720896 = "rw"         # TODO
owner = "woodpecker"
