# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2025 Max Chernoff

[network]
# The IP addresses of the server
ipv4 = "152.53.36.213"
ipv6 = "2a0a:4cc0:2000:172::1"


[woodpecker]
# The port used by the Woodpecker agent to communicate with the Woodpecker
# server
port = "40144"


[registry]
# The port used to push/write to the container registry
port = "23719"


[fedora]
# The version of Fedora to use for all container images
version = "42"


[dns]
# The alternate port that the DNS server will listen on
altport = "25108"


[prometheus]
# Define the IP addresses for the Prometheus subnet
subnet = "10.79.79.1/24"
gateway = "10.79.79.1"

caddy.ip = "10.79.79.2"
caddy.port = "9117"

registry.ip = "10.79.79.3"
registry.port = "9103"

overleaf.ip = "10.79.79.4"
overleaf.port = "9101"

maddy.ip = "10.79.79.5"
maddy.port = "9749"

woodpecker.ip = "10.79.79.6"
woodpecker.port = "9102"

node.ip = "10.79.79.7"
node.port = "9100"

podman.port = "9882"
podman.web.ip = "10.79.79.8"
podman.woodpecker.ip = "10.79.79.9"

knot.ip = "10.79.79.11"
knot.port = "9434"

dmarc-metrics.ip = "10.79.79.12"
dmarc-metrics.port = "9797"

openwrt.port = "9103"

victoria-logs.ip = "10.79.79.13"
victoria-logs.port = "9428"

victoria-metrics.ip = "127.0.0.1"
victoria-metrics.port = "9090"


[email]
# Define the IP addresses for the email server
ipv4 = "10.80.80.1"


[wireguard]
# Define the IP addresses for the WireGuard VPN
subnet.ipv4 = ["10.77.0.0/16", "10.78.1.0/24"]
subnet.ipv6 = ["fd77:0:0:77::/64", "fd77:0:0:78::/64"]

self.ipv4 = "10.78.1.4"
self.ipv6 = "fd77:0:0:78::4"


[victoria-logs]
# The port used to append logs
port = "21660"

# The port that Victoria Logs will listen on for syslog messages
syslog = "514"


[filesystems]
# The UUIDs for the filesystems used by the system
root = "54b902ba-941a-495f-ae19-770ee22681c4"
boot = "26d65031-c51b-4e2c-999f-9642f90ebcab"
efi = "312A-0AD0"
swap = "25c85fb7-eadd-414c-9c56-475bf2a401f4"


# systemd resource control priorities
[priorities]
lowest = """
CPUSchedulingPolicy=idle
CPUWeight=1
CPUQuota=150%

IOSchedulingClass=idle
IOSchedulingPriority=7
IOWeight=1
Nice=19

MemoryMax=6G
"""

low = """
CPUSchedulingPolicy=batch
CPUWeight=20
CPUQuota=350%

IOSchedulingClass=best-effort
IOSchedulingPriority=5
IOWeight=20
Nice=10

MemoryMax=10G
"""

high = """
CPUSchedulingPolicy=other
CPUWeight=200
CPUQuota=

IOSchedulingClass=best-effort
IOSchedulingPriority=3
IOWeight=200
Nice=-5

MemoryMax=12G
"""
