# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2025 Max Chernoff
apiVersion: 1

datasources:
  - name: Victoria Logs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://systemd-victoria-logs:!!victoria-logs.port!!
