# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2026 Max Chernoff

# Base image
FROM quay.io/fedora/fedora-minimal:!!fedora.version!! AS build

# Install the base packages
@dnf_install[install_root=/mnt/build/](
    coreutils-single
    generic-release
    glibc-minimal-langpack
    python3-flask
    python3-waitress
)

@rpm_erase_all_except[install_root=/mnt/build/](
    .*lib.*
    .*python3.*
    basesystem
    filesystem
    setup
    generic-release
    ca-certificates
)

# Create the new container
FROM scratch
COPY --from=build /mnt/build/ /
USER 1000:1000
StopSignal SIGINT
ENTRYPOINT ["/usr/bin/python3"]
