# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff

# Base image
FROM registry.fedoraproject.org/fedora-minimal:41 AS build

# Add the files
COPY ["container-build.sh", "/usr/local/sbin/"]

# Run the build script
RUN /usr/local/sbin/container-build.sh

# Create the new container
FROM scratch
COPY --from=build /mnt/build/ /
USER 1000:1000
ENTRYPOINT ["/usr/bin/python3"]
