# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff

# Base image
FROM quay.io/fedora/fedora-minimal:!!fedora.version!! AS build

# Run the build script
RUN \
    --mount=from=realpath,source=container-build.sh,target=/usr/local/sbin/container-build.sh,ro \
    /usr/local/sbin/container-build.sh

# Create the new container
FROM scratch
COPY --from=build /mnt/build/ /
USER 1000:1000
ENTRYPOINT ["/usr/bin/python3"]
