# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2025 Max Chernoff
global:
  scrape_interval: 60s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "!!prometheus.prometheus.ip!!:!!prometheus.prometheus.port!!"

  - job_name: "caddy"
    static_configs:
      - targets:
          - "!!prometheus.caddy.ip!!:!!prometheus.caddy.port!!"

  - job_name: "container-registry"
    static_configs:
      - targets:
          - "!!prometheus.registry.ip!!:!!prometheus.registry.port!!"

  - job_name: "overleaf"
    static_configs:
      - targets:
          - "!!prometheus.overleaf.ip!!:!!prometheus.overleaf.port!!"

  - job_name: "maddy"
    static_configs:
      - targets:
          - "!!prometheus.maddy.ip!!:!!prometheus.maddy.port!!"

  - job_name: "woodpecker"
    static_configs:
      - targets:
          - "!!prometheus.woodpecker.ip!!:!!prometheus.woodpecker.port!!"
