# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2025 Max Chernoff
global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    metric_relabel_configs:
      - source_labels: [__name__]
        action: keep
        regex: "^(prom|scrape).*"
    static_configs:
      - targets:
          - "prometheus.metrics.internal:!!prometheus.prometheus.port!!"

  - job_name: "caddy"
    metric_relabel_configs: &metric_relabel_configs
      - source_labels: [__name__]
        action: drop
        regex: "^(go|nodejs|openfga|promhttp|python|timer_event_loop)_.*"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "caddy.metrics.internal:!!prometheus.caddy.port!!"

  - job_name: "caddy-cache"
    metric_relabel_configs: *metric_relabel_configs
    metrics_path: "/souin-api/metrics"
    static_configs:
      - targets:
          - "caddy.metrics.internal:!!prometheus.caddy.port!!"

  - job_name: "container-registry"
    metric_relabel_configs: *metric_relabel_configs
    static_configs:
      - targets:
          - "container-registry.metrics.internal:!!prometheus.registry.port!!"

  - job_name: "overleaf"
    metric_relabel_configs: *metric_relabel_configs
    static_configs:
      - targets:
          - "overleaf.metrics.internal:!!prometheus.overleaf.port!!"

  - job_name: "maddy"
    metric_relabel_configs: *metric_relabel_configs
    static_configs:
      - targets:
          - "maddy.metrics.internal:!!prometheus.maddy.port!!"

  - job_name: "woodpecker"
    metric_relabel_configs: *metric_relabel_configs
    static_configs:
      - targets:
          - "woodpecker.metrics.internal:!!prometheus.woodpecker.port!!"

  - job_name: "node"
    metric_relabel_configs: *metric_relabel_configs
    static_configs:
      - targets:
          - "node-exporter.metrics.internal:!!prometheus.node.port!!"

  - job_name: "podman"
    metric_relabel_configs: *metric_relabel_configs
    static_configs:
      - targets:
          - "podman-web.metrics.internal:!!prometheus.podman.port!!"
          - "podman-woodpecker.metrics.internal:!!prometheus.podman.port!!"

  - job_name: "knot"
    metric_relabel_configs: *metric_relabel_configs
    static_configs:
      - targets:
          - "knot.metrics.internal:!!prometheus.knot.port!!"

  - job_name: "grafana"
    metric_relabel_configs:
      - source_labels: [__name__]
        action: keep
        regex: "^(grafana_api_dashboard|grafana_api_response|grafana_apiserver|grafana_build_info|grafana_database|grafana_datasource|grafana_db|grafana_folder|grafana_http|grafana_live|grafana_plugin|grafana_process|grafana_prometheus|grafana_stat).*"
    static_configs:
      - targets:
          - "systemd-grafana:3000"

  - job_name: "dmarc-metrics"
    metric_relabel_configs: *metric_relabel_configs
    static_configs:
      - targets:
          - "dmarc.metrics.internal:!!prometheus.dmarc-metrics.port!!"

  - job_name: "systemd"
    metric_relabel_configs: *metric_relabel_configs
    static_configs:
      - targets:
          - "systemd-max.metrics.internal:!!prometheus.systemd.port!!"
          - "systemd-web.metrics.internal:!!prometheus.systemd.port!!"
          - "systemd-tex.metrics.internal:!!prometheus.systemd.port!!"
          - "systemd-woodpecker.metrics.internal:!!prometheus.systemd.port!!"
          - "systemd-builder.metrics.internal:!!prometheus.systemd.port!!"
          - "systemd-system.metrics.internal:!!prometheus.systemd.port!!"
