# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2025 Max Chernoff
global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    metric_relabel_configs:
      - source_labels: [__name__]
        action: keep
        regex: "^(prometheus_(config|engine|http|remote|target)|scrape)_.*"
    static_configs:
      - targets:
          - "prometheus.metrics.maxchernoff.ca:!!prometheus.prometheus.port!!"

  - job_name: "caddy"
    metric_relabel_configs: &metric_relabel_configs
      - source_labels: [__name__]
        action: drop
        regex: "^(go|nodejs|openfga|promhttp|python|timer_event_loop)_.*"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "caddy.metrics.maxchernoff.ca:!!prometheus.caddy.port!!"

  - job_name: "caddy-cache"
    metric_relabel_configs: *metric_relabel_configs
    metrics_path: "/souin-api/metrics"
    static_configs:
      - targets:
          - "caddy.metrics.maxchernoff.ca:!!prometheus.caddy.port!!"

  - job_name: "container-registry"
    metric_relabel_configs: *metric_relabel_configs
    static_configs:
      - targets:
          - "container-registry.metrics.maxchernoff.ca:!!prometheus.registry.port!!"

  - job_name: "overleaf"
    metric_relabel_configs: *metric_relabel_configs
    static_configs:
      - targets:
          - "overleaf.metrics.maxchernoff.ca:!!prometheus.overleaf.port!!"

  - job_name: "maddy"
    metric_relabel_configs: *metric_relabel_configs
    static_configs:
      - targets:
          - "maddy.metrics.maxchernoff.ca:!!prometheus.maddy.port!!"

  - job_name: "woodpecker"
    metric_relabel_configs: *metric_relabel_configs
    static_configs:
      - targets:
          - "woodpecker.metrics.maxchernoff.ca:!!prometheus.woodpecker.port!!"

  - job_name: "node"
    metric_relabel_configs: *metric_relabel_configs
    static_configs:
      - targets:
          - "node-exporter.metrics.maxchernoff.ca:!!prometheus.node.port!!"

  - job_name: "podman"
    metric_relabel_configs: *metric_relabel_configs
    static_configs:
      - targets:
          - "podman-web.metrics.maxchernoff.ca:!!prometheus.podman.port!!"
          - "podman-woodpecker.metrics.maxchernoff.ca:!!prometheus.podman.port!!"

  - job_name: "knot"
    metric_relabel_configs: *metric_relabel_configs
    static_configs:
      - targets:
          - "knot.metrics.maxchernoff.ca:!!prometheus.knot.port!!"

  - job_name: "grafana"
    metric_relabel_configs:
      - source_labels: [__name__]
        action: keep
        regex: "^(grafana_api_dashboard|grafana_api_response|grafana_apiserver|grafana_build_info|grafana_database|grafana_datasource|grafana_db|grafana_folder|grafana_http|grafana_live|grafana_plugin|grafana_prometheus|grafana_stat).*"
    static_configs:
      - targets:
          - "systemd-grafana:3000"

  - job_name: "dmarc-metrics"
    metric_relabel_configs: *metric_relabel_configs
    static_configs:
      - targets:
          - "dmarc.metrics.maxchernoff.ca:!!prometheus.dmarc-metrics.port!!"

  - job_name: "openwrt"
    metric_relabel_configs:
      - source_labels: ["type"]
        target_label: "device"
        action: replace
        regex: "^(rx|tx)_(.*)$"
        replacement: "$2"

      - source_labels: ["type"]
        target_label: "direction"
        action: replace
        regex: "^(rx|tx)_(.*)$"
        replacement: "$1"
    static_configs:
      - targets:
          - "rd.duck.tel:!!prometheus.openwrt.port!!"
          - "wifi-ap.rd.duck.tel:!!prometheus.openwrt.port!!"
