# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2026 Max Chernoff

[Manager]
# Record all metrics
DefaultIOAccounting=yes
DefaultIPAccounting=yes
DefaultMemoryAccounting=yes
DefaultTasksAccounting=yes

# Allow all users to decrease their nice levels
DefaultLimitNICE=-5

# Decrease the default timeouts
DefaultTimeoutStopSec=15s
DefaultDeviceTimeoutSec=15s
DefaultTimeoutStartSec=15s

# Wait 1 second before restarting failed services
DefaultRestartSec=1s

# Sandboxing
SystemCallArchitectures=native
CapabilityBoundingSet=~\
    CAP_MAC_ADMIN \
    CAP_MAC_OVERRIDE \
    CAP_SYS_PACCT \
    CAP_SYS_RAWIO \
    CAP_SYS_RESOURCE

DefaultRestrictSUIDSGID=true
ManagerEnvironment=SYSTEMD_PAGERSECURE=true

# Enable the watchdog
RuntimeWatchdogSec=1min
RebootWatchdogSec=1min
KExecWatchdogSec=1min

# Reboot if systemd itself crashes
CrashAction=reboot
