# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff

# Base image
FROM registry.fedoraproject.org/fedora-minimal:!!fedora.version!! AS build

# Add the files
COPY ["container-build.sh", "/usr/local/sbin/"]
COPY --chmod=644 ["cgi.py", "/root/"]

# Run the build script
RUN /usr/local/sbin/container-build.sh

# Pull Caddy
FROM maxchernoff.ca/caddy:latest AS caddy

# Pull Anubis
FROM ghcr.io/techarohq/anubis:latest AS anubis

# Create the new container
FROM scratch

COPY --chmod=644 ["dbip-asn-lite.mmdb", "/usr/local/share/GeoIP/"]
COPY --from=anubis /ko-app/anubis /usr/local/bin/anubis
COPY --from=caddy /usr/bin/caddy /usr/local/bin/caddy
COPY --from=build /mnt/build/ /
COPY --chmod=755 ["start.py", "/usr/local/bin/"]

USER 1000:1000
CMD ["/usr/local/bin/start.py"]
