export DRACUT_NO_XATTR=1
add_dracutmodules+=" bootc "  # To mount the composefs root
add_dracutmodules+=" busybox " # For debugging and rescue
filesystems+=" btrfs overlay vfat "
hostonly="no"
compress="zstd"
do_strip="yes"
aggressive_strip="yes"
reproducible="yes"
