# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2025 Max Chernoff
docker:
    maxchernoff.ca:
        use-sigstore-attachments: true
    "localhost:23719":
        use-sigstore-attachments: true
