# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2026 Max Chernoff

# From /etc/ssh/sshd_config.d/50-redhat.conf
SyslogFacility AUTHPRIV
PrintMotd no

# Needed with Fedora, unfortunately
UsePAM yes

# Disable X11 forwarding
X11Forwarding no

# Only allow public key authentication
PubkeyAuthentication yes
AuthenticationMethods publickey
PasswordAuthentication no
GSSAPIAuthentication no
KbdInteractiveAuthentication no

# Block failed login attempts
MaxAuthTries 1
MaxStartups 60:30:100
LoginGraceTime 10
PerSourceNetBlockSize 32:64
PerSourcePenalties authfail:1m noauth:1m grace-exceeded:1m crash:5m

# Only allow a single algorithm for each category to reduce attack surface.
# I've chosen the first (aka most preferred) algorithm in the list of OpenSSH's
# defaults as of 2026-07-24.
Ciphers chacha20-poly1305@openssh.com
FingerprintHash sha256
HostKeyAlgorithms ssh-ed25519
KexAlgorithms mlkem768x25519-sha256
MACs umac-64-etm@openssh.com
PubkeyAcceptedAlgorithms ssh-ed25519
