# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff

# Base image
FROM maxchernoff.ca/tex:latest

RUN dnf install \
    --assumeyes \
    --nodocs \
    --setopt=install_weak_deps=False \
    --setopt=keepcache=true \
    wine-core && \
    wine64 "$(type -p texlua.exe)" --help
