# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff

# Base image
FROM maxchernoff.ca/tex:latest

RUN \
    for _ in $(seq 3); do \
        dnf install \
            --assumeyes \
            --nodocs \
            --setopt=install_weak_deps=False \
            --setopt=keepcache=true \
            wine-core \
        && break \
        || sleep $((30 + RANDOM % 90)); \
    done \
    && wine64 "$(type -p texlua.exe)" --help
