# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2026 Max Chernoff

# Remove some modules we don't need
omit_dracutmodules+=" clevis-pin-tpm2 "
omit_dracutmodules+=" fido2 "
omit_dracutmodules+=" lunmask "
omit_dracutmodules+=" nvdimm "
omit_dracutmodules+=" pkcs11 "
omit_dracutmodules+=" systemd-battery-check "
omit_dracutmodules+=" systemd-pcrphase "
omit_dracutmodules+=" tpm2-tss "

# Remove some files we don't need
remove_items+=" /etc/services "
i18n_install_all="no"
