# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2026 Max Chernoff

export DRACUT_NO_XATTR=1
add_dracutmodules+=" bootc "  # To mount the composefs root
add_dracutmodules+=" busybox " # For debugging and rescue
filesystems+=" btrfs overlay vfat "
hostonly="no"
compress="zstd"
do_strip="yes"
aggressive_strip="yes"
reproducible="yes"
