# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2026 Max Chernoff

add_dracutmodules+=" systemd-networkd clevis-pin-tang " # Full-disk encryption
install_items+=" $systemdsystemunitdir/initrd-copy-network.service "
install_items+=" $systemdsystemunitdir/sysefi.mount "
install_items+=" $systemdsystemunitdir/systemd-networkd.service.wants/initrd-copy-network.service "
