# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2026 Max Chernoff

# Enable unlocking over the network with Clevis and Tang
add_dracutmodules+=" clevis-pin-tang clevis-pin-sss "

# Required for Clevis to be able to access the network
add_dracutmodules+=" systemd-networkd "

# Use the static network configuration stored on the ESP
install_items+=" $systemdsystemunitdir/initrd-copy-network.service "
install_items+=" $systemdsystemunitdir/sysefi.mount "
install_items+=" $systemdsystemunitdir/systemd-networkd.service.wants/initrd-copy-network.service "
