# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2026 Max Chernoff

# Workaround for building in a container
export DRACUT_NO_XATTR=1

# To mount the composefs root
add_dracutmodules+=" bootc "
filesystems+=" overlay "

# Install the user databases
install_items+=" /etc/passwd /etc/group "

# Make the initramfs reproducible
reproducible="yes"
