# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff

# Base image
FROM quay.io/fedora/fedora-minimal:!!fedora.version!!

# Add the files
COPY [ \
    "context-cache.tex", \
    "latex-cache.tex", \
    "tex-cache.sh", \
    "/opt/make-font-cache/" \
]

# Set the environment variables
ENV PATH="/opt/texlive/bin/x86_64-linux:/opt/context/texmf-linux-64/bin:/opt/texlive/bin/windows:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin"

@run[mounts=tex](
    /opt/make-font-cache/tex-cache.sh
)

# Install the packages
@dnf_install(
    # Base dependencies
    git
    libxcrypt-compat  # For `biber`

    # For TeX Live
    perl-File-Find
    perl-interpreter
    perl-LWP-Protocol-https
    tar
    xz

    # gucci-on-fleek/lua-widow-control
    curl
    libxslt
    moreutils
    pandoc
    poppler-utils

    # gucci-on-fleek/extractbb
    diffutils
    groff-perl
    parallel
    perl-Compress-Zlib

    # gucci-on-fleek/context-packaging
    add-determinism
    dos2unix # For EOL conversion
    llvm # For `llvm-lipo`
    prename
    zip

    # gucci-on-fleek/context-wiki-mirror
    uv
    vips

    # anss-ce/ANSS-CE
    make
)
