# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff

# Base image
FROM quay.io/fedora/fedora-minimal:!!fedora.version!!

# Set the environment variables
ENV PATH="/opt/texlive/bin/x86_64-linux:/opt/context/texmf-linux-64/bin:/opt/texlive/bin/windows:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin"

# Generate the TeX caches
RUN \
    --mount=type=bind,source=./make-font-cache,target=/root/make-font-cache,rw \
    /root/make-font-cache/tex-cache.sh

# Install the packages
RUN \
    --mount=type=bind,source=./package-install.sh,target=/usr/local/sbin/package-install.sh,ro \
    /usr/local/sbin/package-install.sh
