# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2026 Max Chernoff

# Base image
FROM maxchernoff.ca/tex:latest

@dnf_install(
    byacc
    flex
    gcc
    make
    texinfo
    zig
)

@set_layer[
    layer_name=tex-files,
    update_frequency=monthly,
](
    /opt/make-font-cache*
)

@set_layer[
    layer_name=texlive-cache,
    update_frequency=daily,
](
    /root/.texlive*
)

@set_layer[
    layer_name=context-cache,
    update_frequency=daily,
](
    /root/luametatex-cache*
    /root/luatex-cache*
)
