# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2026 Max Chernoff

#Type  Path                        Mode  User  Group  Age  Argument
v-     /var/lib/bees               0700  bees  bees   -    -
f      /var/lib/bees/beeshash.dat  0600  bees  bees   -    -

