# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2026 Max Chernoff

#Type  Path                                 Mode  User  Group  Age  Argument
w      /sys/kernel/mm/ksm/run               -     -     -      -    1
w!-    /sys/kernel/mm/ksm/pages_to_scan     -     -     -      -    5000
w      /sys/kernel/mm/ksm/advisor_mode      -     -     -      -    scan-time
w      /sys/kernel/mm/ksm/adivsor_max_cpu   -     -     -      -    50
w      /sys/kernel/mm/ksm/max_page_sharing  -     -     -      -    65535

