# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2026 Max Chernoff

#Type  Path                                               Mode  User  Group  Age  Argument
w      /sys/kernel/mm/transparent_hugepage/enabled        -     -     -      -    always
w      /sys/kernel/mm/transparent_hugepage/shmem_enabled  -     -     -      -    always
