# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2026 Max Chernoff

#Type  Path                                           Mode  User  Group  Age  Argument
w      /proc/sys/vm/min_free_kbytes                   -     -     -      -    204000
w      /proc/sys/vm/swappiness                        -     -     -      -    100
w      /proc/sys/vm/watermark_scale_factor            -     -     -      -    250
w      /sys/module/zswap/parameters/compressor        -     -     -      -    zstd
w      /sys/module/zswap/parameters/enabled           -     -     -      -    1
w      /sys/module/zswap/parameters/max_pool_percent  -     -     -      -    33
w      /sys/module/zswap/parameters/shrinker_enabled  -     -     -      -    1



