# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2026 Max Chernoff

tag_domain = "maxchernoff.ca"
registry = "localhost:!!registry.port!!"
sigstore_path = "/var/home/repo/credentials/builder/sigstore-builder.yaml"
git_directory = "/var/home/repo/maxchernoff.ca/.git"
filesystem_to_git_prefix = "/var/home/"
distributor = "Max Chernoff"

containers_policy = """{
    "transports": {
        "docker": {
            "maxchernoff.ca": [
                {
                    "type": "sigstoreSigned",
                    "rekorPublicKeyData": "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFMkcyWSsydGFiZFRWNUJjR2lCSXgwYTlmQUZ3cgprQmJtTFNHdGtzNEwzcVg2eVlZMHp1ZkJuaEM4VXIvaXk1NUdoV1AvOUEvYlkyTGhDMzBNOStSWXR3PT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCgo=",
                    "keyData": "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFdU51aWh1SUpOSFhvUUVacTF5SHZPZkZZU1gwYgpYMjlMVUYremQzdWVHS3RKV1Z4WlFJWEJCZVN4YnBxV1djdDQzR1RoUE44QmFHbWpDT0tDTjNrWUp3PT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCgo="
                }
            ]
        }
    }
}"""

[[mounts]]
type = "cache"
name = "dnf"
host_path = "~/.cache/podman-dnf/"
container_path = "/var/cache/libdnf5/"

[[mounts]]
type = "read-only"
category = "tex"
host_path = "/var/home/tex/context"
container_path = "/opt/context"

[[mounts]]
type = "read-only"
category = "tex"
host_path = "/var/home/tex/texlive"
container_path = "/opt/texlive"

[[mounts]]
type = "cache"
category = "go"
host_path = "~/.cache/go-build/"
container_path = "/root/.cache/go-build/"

[[mounts]]
type = "cache"
category = "go"
host_path = "~/.cache/go-modules"
container_path = "/go/"

[[mounts]]
type = "read-only"
category = "system-config"
host_path = "/var/home/repo/maxchernoff.ca/etc/common"
container_path = "/run/system-config/etc"

[[mounts]]
type = "read-only"
category = "system-config"
host_path = "/var/home/repo/maxchernoff.ca/usr"
container_path = "/run/system-config/usr"
