#!/bin/sh
# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff
set -eu

printf \
    'Date:\t%s\nVersion:\t%s\nUptime:\t%s\nLoad Average:\t%s, %s, %s%.0s%.0s\n' \
    "$(date '+%A, %-d %B %Y, %-I:%0M%P')" \
    "$(rpm-ostree status --booted --jsonpath='.deployments[0].version' | grep -oP '[.\d]+')" \
    "$(uptime --pretty | sed 's/up //')" \
    $(cat /proc/loadavg) \
| column --table --separator="$(printf '\t')"
echo

(
    systemctl --user -M web@ list-units --with-dependencies --quiet --all \
        caddy.service \
        overleaf-pod.service \
        podman-auto-update.service \
        podman-auto-update.timer \
        update-analytics.target \
        update-analytics.timer \
        woodpecker-server.service \
    | sed 's/^/\0 web/' \
    && systemctl --user -M woodpecker@ list-units --with-dependencies --quiet --all \
        podman-auto-update.service \
        podman-auto-update.timer \
        woodpecker-agent.service \
    | sed 's/^./\0 woodpecker/' \
    && systemctl --user -M tex@ list-units --with-dependencies --quiet --all \
        update-texlive.service \
        update-texlive.timer \
    | sed 's/^./\0 tex/' \
    && systemctl --system list-units --quiet --all \
        fail2ban.service \
        rpm-ostreed-automatic.service \
        rpm-ostreed-automatic.timer \
        snapper-cleanup.service \
        snapper-cleanup.timer \
        snapper-timeline.service \
        snapper-timeline.timer \
    | sed 's/^./\0 system/'
) \
| tr --squeeze-repeats ' ' \
| cut --delimiter=' ' --fields=1-5 \
| sort --field-separator=' ' --key=3 \
| uniq \
| grep --extended-regexp --invert-match 'network-online.target|app.slice|basic.target|-network.service' \
| column --table --separator=' ' \
| grep --color=always --extended-regexp '●|not-found|bad-setting|error|failed|dead|start|reload|stop|$'
