#!/usr/bin/env python3
# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff

###############
### Imports ###
###############

from smtplib import SMTP
from email.message import EmailMessage
from argparse import ArgumentParser
from getpass import getuser


#################
### Constants ###
#################

SMTP_SERVER = "localhost"
SMTP_PORT = 587
EMAIL_FROM = "server@noreply.maxchernoff.ca"
EMAIL_TO = "server-status@maxchernoff.ca"
PASSWORD_FILE = f"/var/home/repo/credentials/{EMAIL_FROM}"


###################
### Entry Point ###
###################

if __name__ != "__main__":
    raise ImportError("This script is not meant to be imported")

parser = ArgumentParser(
    prog="email-failure",
    description="Send an email to the admin when a service fails.",
)

parser.add_argument(
    "service",
    type=str,
    help="The name of the service that failed.",
)

args = parser.parse_args()

msg = EmailMessage()
msg["Subject"] = f"Service Failure: {args.service} ({getuser()})"
msg["From"] = EMAIL_FROM
msg["To"] = EMAIL_TO
msg.set_content(f'The service "{args.service}" has failed.')

with open(PASSWORD_FILE, "r") as f:
    password = f.read().strip()

with SMTP(SMTP_SERVER, SMTP_PORT) as smtp:
    smtp.login(EMAIL_FROM, password)
    smtp.send_message(msg)
