#!/usr/bin/env bash
# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff
set -euo pipefail

ptys=$(who --message | awk '/+/ {print $3}')

for pty in $ptys; do
    printf "\n\e[0;1;2;37mServer updated at %s.\e[0m\n" "$(date +'%-l:%M%P')" > /dev/$pty
done
