#!/bin/sh
set -eu
if [ "$(id -u)" -eq 0 ]; then
    echo "Must not run as root"
    exit 1
fi
script_dir="$(dirname "$(realpath "$0")")"

cd $script_dir
git fetch
git reset --hard origin/master
restorecon -R /var/home/max/maxchernoff.ca/web
