#!/usr/bin/env python3
# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff

###############
### Imports ###
###############

from pathlib import Path
from sys import argv

from process_files import config

###################
### Entry Point ###
###################

if __name__ == "__main__":
    path = Path(argv[1])
    config.verbose = True
    config.dry_run = True
    config.load_and_process_config(path)
