#!/usr/bin/env python3
# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff

###############
### Imports ###
###############

from sys import argv
from pathlib import Path

import process_files.acl as acl


###################
### Entry Point ###
###################

if __name__ == "__main__":
    path = Path(argv[1])
    acl.process_file(path)
