#!/bin/sh
# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff
set -eu
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

watch_cmd="watch --color -n1"
if [ -z ${1+x} ]; then
    watch_cmd="sh -c"
fi

$watch_cmd "\
    SYSTEMD_COLORS=1 systemctl --user -M web@ list-units --with-dependencies --quiet --all \
        caddy.service \
        overleaf-pod.service \
        podman-auto-update.{timer,service} \
        update-analytics.{timer,target} \
        woodpecker-server.service \
    | grep --invert-match network-online.target \
    && SYSTEMD_COLORS=1 systemctl --user -M woodpecker@ list-units --with-dependencies --quiet --all \
        podman-auto-update.{timer,service} \
        woodpecker-agent.service \
    | grep --invert-match network-online.target \
    && SYSTEMD_COLORS=1 systemctl --user -M tex@ list-units --with-dependencies --quiet --all \
        update-texlive.{timer,service} \
    | grep --invert-match network-online.target \
"
