#!/bin/sh
set -eu
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

watch -n1 "systemctl --user -M web@ list-units --with-dependencies --quiet --all overleaf-pod.service caddy.service"
