#!/bin/sh
# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff
set -eu

# Check the permissions
if [ "$(id -u)" -eq 0 ]; then
    echo "Must not run as root"
    exit 1
fi

# Always run from the root of the repository
script_dir="$(dirname "$(realpath "$0")")"
root_dir="$(realpath "$script_dir/..")"
cd "$root_dir"

# Update the repository
git fetch --recurse-submodules=yes
git reset --recurse-submodules --hard origin/master
git submodule update --init --recursive --checkout --force

# Update the SELinux contexts
restorecon -R /var/home/max/maxchernoff.ca/
