#!/bin/sh
set -eu
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

restorecon -Rv /var/home/max/maxchernoff.ca/web
systemctl --user -M web@ daemon-reload
systemctl --user -M web@ restart overleaf-pod.service caddy.service
