#!/bin/sh
# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff
set -eu

# Check the permissions
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

# Always run from the root of the repository
script_dir="$(dirname "$(realpath "$0")")"
root_dir="$(realpath "$script_dir/..")"
cd "$root_dir"

# Update the symlinks
stow_cmd="stow --dir=$root_dir --restow"

for user in max tex web woodpecker; do
    $stow_cmd --target="/var/home/$user" "$user"
    systemctl --user --machine "$user@" daemon-reload
done
