#!/bin/sh
# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff
set -eu
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

systemctl --user -M web@ daemon-reload
systemctl --user -M web@ restart overleaf-pod.service caddy.service
