#!/usr/bin/env python3
# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff

###############
### Imports ###
###############

from argparse import ArgumentParser, FileType
from os import geteuid
from pathlib import Path
from pprint import pprint

from process_files import config

###################
### Entry Point ###
###################

if __name__ != "__main__":
    raise ImportError("This script is not meant to be imported")

script_path = Path(__file__).resolve()
default_path = script_path.parent.parent / "install-rules.toml"

parser = ArgumentParser(
    prog="web-install",
    description="Declaratively copies, links, and sets permissions for files.",
)

parser.add_argument(
    "-v",
    "--verbose",
    action="store_true",
    help="Print verbose output",
)

parser.add_argument(
    "-n",
    "--dry-run",
    action="store_true",
    help="Print what would be done without actually doing it",
)

parser.add_argument(
    "config_file",
    type=FileType("rb"),
    nargs="?",
    help="The configuration file to build. (Default: $repo_root/install-rules.toml)",
    default=default_path,
)

args = parser.parse_args()

if geteuid() != 0:
    raise PermissionError("This script must be run as root")

config.verbose = args.verbose
config.dry_run = args.dry_run

if isinstance(args.config_file, Path):
    args.config_file = args.config_file.open("rb")
config.process_config(args.config_file)
