#!/bin/sh
# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff
set -eu
if [ "$(id -u)" -eq 0 ]; then
    echo "Must not run as root"
    exit 1
fi

script_dir="$(dirname "$(realpath "$0")")"
repo_dir="$(realpath "$script_dir/..")"
cd $repo_dir

if [ "${1:-}" = "knot" ]; then
    podman run \
        --pull=newer \
        --network=host \
        --rm \
        --interactive \
        --tty \
        --volume=./web/knot/config:/config:ro,z \
        docker.io/cznic/knot:latest \
        /usr/sbin/knotd
    exit 0
fi

if [ "${1:-}" = "caddy" ]; then
    # podman run \
    #     --pull=newer \
    #     --network=host \
    #     --rm \
    #     --interactive \
    #     --tty \
    #     --volume=./web/caddy/etc/:/etc/caddy:z,ro \
    #     --volume=./web/caddy/static:/srv/:z,ro \
    #     maxchernoff.ca/caddy:latest \
    #     caddy run \
    #     --watch \
    #     --adapter caddyfile \
    #     --config /etc/caddy/local.caddyfile
    caddy run \
        --watch \
        --adapter caddyfile \
        --config ./web/caddy/etc/local.caddyfile
    exit 0
fi

echo "Usage: $0 [knot|caddy]"
exit 1
