# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff

# Base image
FROM registry.fedoraproject.org/fedora-minimal:40

# Run the install script
COPY container-build.sh /usr/local/sbin/container-build.sh
RUN /usr/local/sbin/container-build.sh

# Set the environment variables
ENV PATH="/opt/texlive/bin/x86_64-linux:/opt/context/texmf-linux-64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin"
