# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff

# Base image
FROM registry.fedoraproject.org/fedora-minimal:40

# Add the files
COPY ["tex-cache.sh", "package-install.sh", "/usr/local/sbin/"]
COPY ["context-cache.tex", "latex-cache.tex", "/root/"]

# Set the environment variables
ENV PATH="/opt/texlive/bin/x86_64-linux:/opt/context/texmf-linux-64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin"

# Generate the TeX caches
RUN /usr/local/sbin/tex-cache.sh

# Install the packages
RUN /usr/local/sbin/package-install.sh
