# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2026 Max Chernoff

FROM quay.io/fedora/fedora-minimal:!!fedora.version!! AS build

# Install the packages
@dnf_install[
    install_root=/mnt/build/,
    documentation=true,
](
    # Base system
    authselect  # PAM configuration
    btrfs-progs  # /usr/bin/btrfs
    dbus-broker
    fedora-release-iot
    firewalld
    glibc-langpack-en
    glibc-minimal-langpack
    iproute  # /usr/bin/ip
    kernel-modules-core  # Do not install the extra kernel modules
    openssh-clients
    openssh-server
    selinux-policy-targeted
    sudo
    systemd
    systemd-networkd
    systemd-pam
    systemd-resolved

    # Booting and updating
    bootc
    clevis-dracut  # Full disk encryption
    dnf5
    dosfstools  # fsck for the EFI partition
    dracut-network
    efibootmgr
    fwupd-efi
    strip  # To strip the initramfs and kernel for smaller size
    systemd-boot-unsigned
    systemd-ukify  # Creates a unified kernel image (UKI) for booting

    # Command-line Utilities
    acl  # /usr/bin/{getfacl/setfacl}
    busybox
    curl
    fish
    git-core  # "-core" excludes the Perl-based extra utilities
    gnupg2  # GPG
    htop
    iputils  # /usr/bin/ping, etc.
    jq
    less
    man-db  # man pages
    man-pages  # man pages
    policycoreutils-python-utils  # /usr/bin/semanage
    python3-cryptography
    python3-pystemd
    ripgrep
    setools-console
    strace
    tmux
    traceroute
    vim-enhanced  # "-enhanced" is required for syntax highlighting

    # TeX
    perl-File-Find  # Required by tlmgr
    perl-interpreter  # Required by tlmgr
    perl-LWP-Protocol-https  # Recommended for tlmgr
    tar  # Required by tlmgr
    xz  # Required by tlmgr
    fontconfig  # Required by XeTeX

    # System Services
    audit-rules  # /usr/bin/auditctl
    bees  # Btrfs deduplication
    borgbackup
    btrfsmaintenance
    chrony  # NTP client
    node-exporter  # Prometheus metrics for the entire system
    qemu-guest-agent  # Recommended for a VM guest
    snapper  # Btrfs snapshot management
    systemd-journal-remote  # For journald remote logging
    systemd-oomd-defaults

    # Containers
    podman
    prometheus-podman-exporter  # Prometheus metrics for Podman containers
    systemd-container  # /usr/bin/systemd-nspawn
    udica  # Extra SELinux rules for containers
    skopeo  # For copying container images
)

# Copy over our custom configuration files
@run[mounts=system-config](
    cp --archive --no-target-directory /run/system-config/ /mnt/build/
)

# Switch to the new root
FROM scratch
COPY --chown=0:0 --from=build /mnt/build/ /

# Run some custom configuration commands
@with_commit_info()
@run(
    # Only use the services that we've explicitly enabled
    rm -rf /etc/systemd/{system,user}/*
    systemctl --system preset-all
    systemctl --user --global preset-all

    # Generate fish completions for the whole system
    fish -c "fish_update_completions --directory=/usr/share/fish/generated_completions"

    # Remove FIPS stuff
    rpm --query --list crypto-policies | grep -i fips | xargs rm -rf || true

    # Apply the authselect profile
    authselect apply-changes

    # Adjust the "os-release" files
    sed -Ei '/^(IMAGE_ID|IMAGE_VERSION|ARCHITECTURE|VARIANT|VARIANT_ID|RELEASE_TYPE|EXPERIMENT|EXPERIMENT_URL)=/d' \
        /usr/lib/os-release
    {
        echo IMAGE_ID="'maxchernoff.ca-fedora-bootc'"
        echo IMAGE_VERSION="'${COMMIT_INFO}'"
        echo ARCHITECTURE="'x86-64'"
        echo VARIANT="'Personal bootc container'"
        echo VARIANT_ID="'personal-bootc'"
        echo RELEASE_TYPE="'experiment'"
        echo EXPERIMENT="'Personal bootc container'"
        echo EXPERIMENT_URL="'https://github.com/gucci-on-fleek/maxchernoff.ca'"
    } | tee --append /usr/lib/os-release
    rm --force /etc/os-release
    ln --symbolic /usr/lib/os-release /etc/os-release

    # Remove files that shouldn't be in "/var/"
    mv /var/lib/alternatives /usr/lib/alternatives
    rm --force /var/lib/authselect/checksum

    # Move the SELinux policy
    echo "store-root=/etc/selinux" >> /etc/selinux/semanage.conf
    cp --archive --no-target-directory \
        /var/lib/selinux/targeted /etc/selinux/targeted
    rm -rf /var/lib/selinux/

    # Run image-minimizer
    INSTALL_ROOT=/ /usr/bin/image-minimizer.py /etc/image-minimize.conf

    # Rebuild the SELinux modules
    semanage user --modify user_u --range s0-s0:c0.c1023
    semanage login --modify --seuser sysadm_u --range 's0-s0:c0.c1023' root
    semanage login --modify --seuser user_u --range 's0-s0:c0.c1023' __default__
    semodule --install=/etc/selinux/local-policies/local-required-fallbacks.cil

    # Reset the machine-specific resources
    rm --force \
        /var/lib/systemd/random-seed \
        /etc/machine-id \
        /var/lib/systemd/credential.secret \
        /etc/hostname \
        2>/dev/null || true

    # Remove empty directories
    rm -rf /root/
    find / -depth -type d -empty -delete 2>/dev/null || true
    find . -xtype l -delete 2>/dev/null || true
    find / -depth -type d -empty -delete 2>/dev/null || true

    # Restore the intentionally empty directories
    mkdir --parents \
        '/usr/share/empty.sshd' \
        '/usr/share/empty'

    # Add the bootc links
    systemd-tmpfiles --create --boot \
        /usr/lib/tmpfiles.d/bootc-build.conf \
        /usr/lib/tmpfiles.d/tmp.conf

    # Move the user database to /usr/lib
    systemd-sysusers
    mkdir --parents /usr/lib/userdb/
    {
        userdbctl user \
            --with-dropin=false \
            --json=short \
            --disposition=intrinsic \
            --disposition=system \
            --disposition=regular
        userdbctl group \
            --with-dropin=false \
            --json=short \
            --disposition=intrinsic \
            --disposition=system \
            --disposition=regular
    } \
    | jq --raw-output '
        del(
            .status,
            .passwordChangeNow,
            .lastPasswordChangeUSec,
            .passwordChangeMaxUSec,
            .passwordChangeWarnUSec
        )
        | . + {privileged: {hashedPassword: "!*"}, locked: true}
        | tostring
    ' | while read -r json; do
        user="$(echo "$json" | jq --raw-output '.userName | values')"
        group="$(echo "$json" | jq --raw-output '.groupName | values')"
        uid="$(echo "$json" | jq --raw-output '.uid | values')"
        gid="$(echo "$json" | jq --raw-output '.gid | values')"

        if [ -n "$user" ]; then
            echo "$json" | jq . > "/usr/lib/userdb/${user}.user"
            ln --symbolic --force \
                "/usr/lib/userdb/${user}.user" \
                "/usr/lib/userdb/${uid}.user"
        fi

        if [ -n "$group" ]; then
            echo "$json" | jq . > "/usr/lib/userdb/${group}.group"
            ln --symbolic --force \
                "/usr/lib/userdb/${group}.group" \
                "/usr/lib/userdb/${gid}.group"
        fi
    done
    rm --force /etc/passwd* /etc/group* /etc/shadow* /etc/gshadow*

    # Modify the root user
    cat /usr/lib/userdb/root.user | jq '. + {
        homeDirectory: "/var/roothome", shell: "/usr/bin/fish"
    }' | tee /usr/lib/userdb/root.user >/dev/null
)

# Set the metadata
@allow_all_capabilities()
@set_layer[
    layer_name=fish-completions,
    update_frequency=daily,
](
    /usr/share/fish/generated_completions*
)

@set_layer[
    layer_name=custom-configuration,
    update_frequency=weekly,
](
    /usr/*
    /etc/*
)

STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
