# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2026 Max Chernoff
FROM maxchernoff.ca/fedora-bootc-base:latest as base

FROM base as kernel
ARG IMAGE_ID
RUN <<EOF
    set -euxo pipefail
    export SOURCE_DATE_EPOCH=0

    # Get the composefs ID
    {
        echo "graphRootMounted=1"
        echo "imageid=$IMAGE_ID"
    } > /run/.containerenv

    # Add the composefs ID to the kernel command line
    echo "composefs=$(\
        bootc container compute-composefs-digest-from-storage \
    )" >> /etc/kernel/cmdline
    grep --perl-regexp --quiet '^composefs=.{5}' /etc/kernel/cmdline

    # Make sure that Dracut can find the user databases
    userdb_args=(
        --multiplexer="false"
        --output="classic"
        --disposition="system"
        --disposition="regular"
    )
    userdbctl "${userdb_args[@]}" user > /etc/passwd
    userdbctl "${userdb_args[@]}" group > /etc/group

    # UKI generation
    kernel-install add-all

    mkdir -p /boot/EFI/BOOT/ /boot/EFI/systemd/
    cp /usr/lib/systemd/boot/efi/systemd-bootx64.efi /boot/EFI/BOOT/BOOTX64.EFI
    cp /usr/lib/systemd/boot/efi/systemd-bootx64.efi /boot/EFI/systemd/systemd-bootx64.efi

    # Cleanup
    rm -rf /run/containers

    # Lint the bootc container
    bootc container lint --no-truncate --fatal-warnings || true

    # Clamp the timestamps
    find /boot -depth -exec touch --no-dereference --date="@0" '{}' +
EOF

FROM base AS bootable
COPY --from=kernel /boot /boot
