# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2024 Max Chernoff

FROM docker.io/library/caddy:2.9-builder AS builder

ENV GOTOOLCHAIN=auto
ENV GOPRIVATE=github.com/gucci-on-fleek

RUN xcaddy build master \
    --with github.com/caddy-dns/rfc2136 \
    --with github.com/caddyserver/cache-handler \
    --with github.com/caddyserver/replace-response \
    --with github.com/darkweak/storages/otter/caddy \
    --with github.com/mholt/caddy-l4
# --replace github.com/libdns/libdns=github.com/libdns/libdns@draft-1.0 \
# --replace github.com/libdns/rfc2136=github.com/gucci-on-fleek/libdns-rfc2136@libdns-1.0

FROM docker.io/library/caddy:2.9

ENV CADDY_VERSION=ech

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
