# Source Code for maxchernoff.ca
# https://github.com/gucci-on-fleek/maxchernoff.ca
# SPDX-License-Identifier: MPL-2.0+ OR CC-BY-SA-4.0+
# SPDX-FileCopyrightText: 2026 Max Chernoff

FROM docker.io/library/caddy:2.11-builder AS builder

@run[mounts=go](
    xcaddy build \
        --with github.com/caddy-dns/rfc2136 \
        --with github.com/caddyserver/cache-handler \
        --with github.com/caddyserver/replace-response \
        --with github.com/caddyserver/transform-encoder \
        --with github.com/darkweak/storages/otter/caddy \
        --with github.com/mholt/caddy-l4 \
        --with github.com/mholt/caddy-ratelimit \
        --with github.com/porech/caddy-maxmind-geolocation \
        --with maxchernoff.ca/tools/speedtest
)

FROM docker.io/library/caddy:2.11

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

@set_layer[
    layer_name=alpine,
    update_frequency=weekly,
    filter_rpm=false,
](
    /*
)

@set_layer[
    layer_name=caddy-base,
    update_frequency=monthly,
    filter_rpm=false,
](
    /config/caddy*
    /data/caddy*
    /etc/caddy*
    /usr/share/caddy*
)

@set_layer[
    layer_name=caddy-binary,
    update_frequency=daily,
    filter_rpm=false,
](
    /usr/bin/caddy
)
